client_config_backend: settings
client_config:
    client_id: 634459307708-p769e74vg9e6bj1odctuodka7s9cisis.apps.googleusercontent.com
    client_secret: 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
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive
